package format

import (
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The conformance runner checks this implementation against the committed
// vectors in fixtures/format-v2/.
//
// For Go this is a regression guard rather than an independent check: the
// vectors are generated by cmd/mkvectors, which uses this package. Its value is
// that any change to the format code makes the committed vectors fail, forcing
// a deliberate regeneration and a visible diff instead of a silent format
// change. The same runner shape is what the C and Rust implementations must
// satisfy, where the check is genuinely independent.

const vectorDir = "../../fixtures/format-v2"

type vectorExpectation struct {
	Name        string `json:"name"`
	Description string `json:"description"`

	Scan *struct {
		StopReason         string         `json:"stop_reason"`
		FramesRetained     int            `json:"frames_retained"`
		StopOffset         int            `json:"stop_offset"`
		DiscardedTailBytes uint32         `json:"discarded_tail_bytes"`
		UnknownTypeCount   int            `json:"unknown_type_count"`
		RecordCounts       map[string]int `json:"record_counts"`
		FirstSeq           *uint32        `json:"first_seq"`
		LastSeq            *uint32        `json:"last_seq"`
	} `json:"scan"`

	Header *struct {
		ParseError string `json:"parse_error"`
	} `json:"header"`

	Manifest *struct {
		Valid              bool   `json:"valid"`
		SignatureValid     bool   `json:"signature_valid"`
		ContentRootHex     string `json:"content_root_hex"`
		DevicePublicKeyHex string `json:"device_public_key_hex"`
		CanonicalBytesHex  string `json:"canonical_bytes_sha256_hex"`
	} `json:"manifest"`

	Receipt *struct {
		SignatureValid     bool   `json:"signature_valid"`
		Acknowledges       bool   `json:"acknowledges_uploaded_root"`
		UploadedRootHex    string `json:"uploaded_content_root_hex"`
		ReceiptRootHex     string `json:"receipt_content_root_hex"`
		ServerPublicKeyHex string `json:"server_public_key_hex"`
	} `json:"receipt"`

	Merkle *struct {
		RootHex string   `json:"root_hex"`
		Leaves  []string `json:"leaves_hex"`
	} `json:"merkle"`

	Policy *PolicySnapshot `json:"policy"`

	Events *struct {
		Events []struct {
			EventType     uint8  `json:"event_type"`
			EventTypeName string `json:"event_type_name"`
			LatE7         int32  `json:"lat_e7"`
			LonE7         int32  `json:"lon_e7"`
			Detail        string `json:"detail"`
		} `json:"events"`
	} `json:"events"`

	Health *struct {
		Records []struct {
			HealthState uint8    `json:"health_state"`
			Names       []string `json:"names"`
		} `json:"records"`
	} `json:"health"`

	Update *struct {
		SignatureValid     bool   `json:"signature_valid"`
		FirmwareVersion    string `json:"firmware_version"`
		MinFirmwareVersion string `json:"min_firmware_version"`
		ImageSHA256Hex     string `json:"image_sha256_hex"`
		ImageLength        uint32 `json:"image_length"`
		UpdateKeyHex       string `json:"update_public_key_hex"`
	} `json:"update"`
}

func TestConformanceVectors(t *testing.T) {
	entries, err := os.ReadDir(vectorDir)
	if err != nil {
		t.Skipf("vectors not generated (%v); run: go run ./cmd/mkvectors -out ../fixtures/format-v2", err)
	}

	checked := 0
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}

		dir := filepath.Join(vectorDir, e.Name())
		raw, err := os.ReadFile(filepath.Join(dir, "expected.json"))
		if err != nil {
			t.Errorf("%s: no expected.json: %v", e.Name(), err)
			continue
		}

		var exp vectorExpectation
		if err := json.Unmarshal(raw, &exp); err != nil {
			// Multi-segment vectors use a different shape; they are covered by
			// TestValidMultiSegment.
			continue
		}

		t.Run(e.Name(), func(t *testing.T) {
			switch {
			case exp.Events != nil, exp.Health != nil:
				// These carry a scan as well, so the frames are walked and the
				// payloads checked against the same bytes.
				checkScanVector(t, dir, &exp)
				if exp.Events != nil {
					checkEventsVector(t, dir, &exp)
				}
				if exp.Health != nil {
					checkHealthVector(t, dir, &exp)
				}
			case exp.Scan != nil:
				checkScanVector(t, dir, &exp)
			case exp.Header != nil:
				checkHeaderVector(t, dir)
			case exp.Manifest != nil:
				checkManifestVector(t, dir, &exp)
			case exp.Receipt != nil:
				checkReceiptVector(t, dir, &exp)
			case exp.Merkle != nil:
				checkMerkleVector(t, &exp)
			case exp.Policy != nil:
				checkPolicyVector(t, dir, &exp)
			case exp.Update != nil:
				checkUpdateVector(t, dir, &exp)
			default:
				t.Skip("no checkable expectation")
			}
		})
		checked++
	}

	if checked == 0 {
		t.Error("no vectors were checked")
	}
	t.Logf("checked %d vectors", checked)
}

func checkScanVector(t *testing.T, dir string, exp *vectorExpectation) {
	t.Helper()

	b, err := os.ReadFile(filepath.Join(dir, "segment.bin"))
	if err != nil {
		t.Fatalf("read segment.bin: %v", err)
	}

	res, err := ScanSegment(b, ScanState{})
	if err != nil {
		t.Fatalf("ScanSegment: %v", err)
	}

	if got := res.Stop.String(); got != exp.Scan.StopReason {
		t.Errorf("stop_reason = %q, want %q (%s)", got, exp.Scan.StopReason, res.StopDetail)
	}
	if len(res.Frames) != exp.Scan.FramesRetained {
		t.Errorf("frames_retained = %d, want %d", len(res.Frames), exp.Scan.FramesRetained)
	}
	if res.StopOffset != exp.Scan.StopOffset {
		t.Errorf("stop_offset = %d, want %d", res.StopOffset, exp.Scan.StopOffset)
	}
	if res.DiscardedTailBytes != exp.Scan.DiscardedTailBytes {
		t.Errorf("discarded_tail_bytes = %d, want %d", res.DiscardedTailBytes, exp.Scan.DiscardedTailBytes)
	}
	if res.UnknownTypeCount != exp.Scan.UnknownTypeCount {
		t.Errorf("unknown_type_count = %d, want %d", res.UnknownTypeCount, exp.Scan.UnknownTypeCount)
	}

	for name, want := range exp.Scan.RecordCounts {
		found := 0
		for rt, n := range res.RecordCounts {
			if rt.String() == name {
				found = n
			}
		}
		if found != want {
			t.Errorf("record_counts[%s] = %d, want %d", name, found, want)
		}
	}

	if exp.Scan.FirstSeq != nil {
		if len(res.Frames) == 0 {
			t.Error("expected frames, got none")
		} else if res.Frames[0].Seq != *exp.Scan.FirstSeq {
			t.Errorf("first_seq = %d, want %d", res.Frames[0].Seq, *exp.Scan.FirstSeq)
		}
	}
	if exp.Scan.LastSeq != nil && len(res.Frames) > 0 {
		if got := res.Frames[len(res.Frames)-1].Seq; got != *exp.Scan.LastSeq {
			t.Errorf("last_seq = %d, want %d", got, *exp.Scan.LastSeq)
		}
	}
}

func checkHeaderVector(t *testing.T, dir string) {
	t.Helper()

	b, err := os.ReadFile(filepath.Join(dir, "segment.bin"))
	if err != nil {
		t.Fatalf("read segment.bin: %v", err)
	}

	if _, err := ScanSegment(b, ScanState{}); err == nil {
		t.Error("expected a header parse error, got none")
	}
}

func checkManifestVector(t *testing.T, dir string, exp *vectorExpectation) {
	t.Helper()

	encoded, err := os.ReadFile(filepath.Join(dir, "manifest.cbor"))
	if err != nil {
		t.Fatalf("read manifest.cbor: %v", err)
	}
	sig, err := os.ReadFile(filepath.Join(dir, "manifest.sig"))
	if err != nil {
		t.Fatalf("read manifest.sig: %v", err)
	}
	pub, err := hex.DecodeString(exp.Manifest.DevicePublicKeyHex)
	if err != nil {
		t.Fatalf("decode device public key: %v", err)
	}

	// The manifest bytes must parse as canonical regardless of signature
	// validity: a bad signature does not make the encoding malformed.
	m, parseErr := ParseManifest(encoded)
	if exp.Manifest.Valid && parseErr != nil {
		t.Fatalf("ParseManifest: %v", parseErr)
	}

	_, verifyErr := VerifyManifest(encoded, sig, ed25519.PublicKey(pub))
	if exp.Manifest.SignatureValid && verifyErr != nil {
		t.Errorf("signature should verify: %v", verifyErr)
	}
	if !exp.Manifest.SignatureValid && verifyErr == nil {
		t.Error("signature verified but the vector expects it to fail")
	}

	if m == nil {
		return
	}

	wantRoot, err := hex.DecodeString(exp.Manifest.ContentRootHex)
	if err != nil {
		t.Fatalf("decode content root: %v", err)
	}
	if string(m.ContentRoot[:]) != string(wantRoot) {
		t.Errorf("content_root = %x, want %x", m.ContentRoot, wantRoot)
	}
	if err := m.VerifyContentRoot(); err != nil {
		t.Errorf("VerifyContentRoot: %v", err)
	}

	// Re-encoding must reproduce the committed bytes exactly. This is the
	// check that catches an accidental encoding change.
	if exp.Manifest.CanonicalBytesHex != "" {
		reencoded, err := m.MarshalCBOR()
		if err != nil {
			t.Fatalf("MarshalCBOR: %v", err)
		}
		digest := sha256.Sum256(reencoded)
		if hex.EncodeToString(digest[:]) != exp.Manifest.CanonicalBytesHex {
			t.Errorf("re-encoded manifest digest = %x, want %s — the encoding changed; "+
				"regenerate the vectors deliberately if this is intended",
				digest, exp.Manifest.CanonicalBytesHex)
		}
	}
}

func checkReceiptVector(t *testing.T, dir string, exp *vectorExpectation) {
	t.Helper()

	encoded, err := os.ReadFile(filepath.Join(dir, "receipt.cbor"))
	if err != nil {
		t.Fatalf("read receipt.cbor: %v", err)
	}
	pub, err := hex.DecodeString(exp.Receipt.ServerPublicKeyHex)
	if err != nil {
		t.Fatalf("decode server public key: %v", err)
	}

	r, err := ParseReceipt(encoded)
	if err != nil {
		t.Fatalf("ParseReceipt: %v", err)
	}

	sigErr := r.Verify(ed25519.PublicKey(pub))
	if exp.Receipt.SignatureValid && sigErr != nil {
		t.Errorf("signature should verify: %v", sigErr)
	}
	if !exp.Receipt.SignatureValid && sigErr == nil {
		t.Error("signature verified but the vector expects it to fail")
	}

	uploaded, err := hex.DecodeString(exp.Receipt.UploadedRootHex)
	if err != nil {
		t.Fatalf("decode uploaded root: %v", err)
	}
	var uploadedRoot [32]byte
	copy(uploadedRoot[:], uploaded)

	ackErr := r.VerifyAcknowledges(ed25519.PublicKey(pub), uploadedRoot)
	if exp.Receipt.Acknowledges && ackErr != nil {
		t.Errorf("receipt should acknowledge the upload: %v", ackErr)
	}
	if !exp.Receipt.Acknowledges && ackErr == nil {
		t.Error("receipt accepted as an acknowledgement but the vector expects rejection")
	}
}

func checkMerkleVector(t *testing.T, exp *vectorExpectation) {
	t.Helper()

	// Leaves present: check the tree construction directly.
	if exp.Merkle.Leaves != nil {
		leaves := make([][32]byte, 0, len(exp.Merkle.Leaves))
		for _, h := range exp.Merkle.Leaves {
			b, err := hex.DecodeString(h)
			if err != nil {
				t.Fatalf("decode leaf: %v", err)
			}
			var l [32]byte
			copy(l[:], b)
			leaves = append(leaves, l)
		}

		root := MerkleRoot(leaves)
		if hex.EncodeToString(root[:]) != exp.Merkle.RootHex {
			t.Errorf("root = %x, want %s", root, exp.Merkle.RootHex)
		}
		return
	}

	// Otherwise it is a content-root vector described by members.json.
	t.Skip("content root checked via members.json in TestContentRootIsOrderIndependent")
}

// checkPolicyVector verifies the committed payload decodes to the expected
// values *and* re-encodes to the same bytes.
//
// The re-encode is the point. Two bundles captured under identical policy must
// have byte-identical snapshots, which is what lets a reader group them without
// trusting the version number — and only a committed payload can demonstrate
// that across implementations.
func checkPolicyVector(t *testing.T, dir string, exp *vectorExpectation) {
	raw, err := os.ReadFile(filepath.Join(dir, "policy.cbor"))
	if err != nil {
		t.Fatalf("read policy.cbor: %v", err)
	}

	got, err := ParsePolicySnapshot(raw)
	if err != nil {
		t.Fatalf("ParsePolicySnapshot: %v", err)
	}

	if *got != *exp.Policy {
		t.Errorf("decoded policy does not match the expectation\n got: %+v\nwant: %+v",
			*got, *exp.Policy)
	}

	reencoded, err := got.MarshalCBOR()
	if err != nil {
		t.Fatalf("MarshalCBOR: %v", err)
	}
	if !bytes.Equal(reencoded, raw) {
		t.Errorf("re-encoding produced %d bytes, want the committed %d — this "+
			"implementation does not produce byte-identical output",
			len(reencoded), len(raw))
	}
}

// checkEventsVector walks the segment and checks every trip event, including
// the unknown type that must be named rather than discarded.
func checkEventsVector(t *testing.T, dir string, exp *vectorExpectation) {
	b, err := os.ReadFile(filepath.Join(dir, "segment.bin"))
	if err != nil {
		t.Fatalf("read segment.bin: %v", err)
	}

	res, err := ScanSegment(b, ScanState{})
	if err != nil {
		t.Fatalf("ScanSegment: %v", err)
	}

	var seen int
	for i := range res.Frames {
		f := &res.Frames[i]
		if f.RecordType != RecordTripEvent {
			continue
		}
		if seen >= len(exp.Events.Events) {
			t.Fatalf("segment holds more events than the expectation names")
		}
		want := exp.Events.Events[seen]
		seen++

		e, err := ParseTripEvent(f.Payload)
		if err != nil {
			t.Errorf("event %d does not parse: %v", seen-1, err)
			continue
		}

		if e.EventType != want.EventType {
			t.Errorf("event %d type = %d, want %d", seen-1, e.EventType, want.EventType)
		}
		if name := EventTypeName(e.EventType); name != want.EventTypeName {
			t.Errorf("event %d name = %q, want %q", seen-1, name, want.EventTypeName)
		}
		if e.LatE7 != want.LatE7 || e.LonE7 != want.LonE7 {
			t.Errorf("event %d position = (%d, %d), want (%d, %d)", seen-1,
				e.LatE7, e.LonE7, want.LatE7, want.LonE7)
		}
		if e.Detail != want.Detail {
			t.Errorf("event %d detail = %q, want %q", seen-1, e.Detail, want.Detail)
		}

		// Re-encoding must reproduce the payload, or an implementation could
		// read these records and not write them.
		reencoded, err := EncodeTripEvent(e.EventType, e.LatE7, e.LonE7, e.Detail)
		if err != nil {
			t.Errorf("event %d will not re-encode: %v", seen-1, err)
		} else if !bytes.Equal(reencoded, f.Payload) {
			t.Errorf("event %d re-encodes to different bytes", seen-1)
		}
	}

	if seen != len(exp.Events.Events) {
		t.Errorf("found %d events, want %d", seen, len(exp.Events.Events))
	}
}

// checkHealthVector walks the segment and checks each degraded-state bitmap,
// including that the reserved bit survives.
func checkHealthVector(t *testing.T, dir string, exp *vectorExpectation) {
	b, err := os.ReadFile(filepath.Join(dir, "segment.bin"))
	if err != nil {
		t.Fatalf("read segment.bin: %v", err)
	}

	res, err := ScanSegment(b, ScanState{})
	if err != nil {
		t.Fatalf("ScanSegment: %v", err)
	}

	var seen int
	for i := range res.Frames {
		f := &res.Frames[i]
		if f.RecordType != RecordDeviceHealth {
			continue
		}
		if seen >= len(exp.Health.Records) {
			t.Fatalf("segment holds more health records than the expectation names")
		}
		want := exp.Health.Records[seen]
		seen++

		h, err := ParseDeviceHealth(f.Payload)
		if err != nil {
			t.Errorf("health record %d does not parse: %v", seen-1, err)
			continue
		}

		if h.HealthState != want.HealthState {
			t.Errorf("health record %d state = %#02x, want %#02x", seen-1,
				h.HealthState, want.HealthState)
		}

		names := HealthStateNames(h.HealthState)
		if len(names) != len(want.Names) {
			t.Errorf("health record %d named %v, want %v", seen-1, names, want.Names)
			continue
		}
		for j := range names {
			if names[j] != want.Names[j] {
				t.Errorf("health record %d name %d = %q, want %q", seen-1, j,
					names[j], want.Names[j])
			}
		}
	}

	if seen != len(exp.Health.Records) {
		t.Errorf("found %d health records, want %d", seen, len(exp.Health.Records))
	}
}

// checkUpdateVector verifies the OTA descriptor signature against the pinned
// update key, which is deliberately not the receipt key.
func checkUpdateVector(t *testing.T, dir string, exp *vectorExpectation) {
	encoded, err := os.ReadFile(filepath.Join(dir, "descriptor.cbor"))
	if err != nil {
		t.Fatalf("read descriptor.cbor: %v", err)
	}
	sig, err := os.ReadFile(filepath.Join(dir, "descriptor.sig"))
	if err != nil {
		t.Fatalf("read descriptor.sig: %v", err)
	}

	keyRaw, err := hex.DecodeString(exp.Update.UpdateKeyHex)
	if err != nil || len(keyRaw) != ed25519.PublicKeySize {
		t.Fatalf("update_public_key_hex is not a 32-byte key")
	}

	d, err := VerifyUpdateDescriptor(encoded, sig, ed25519.PublicKey(keyRaw))
	switch {
	case exp.Update.SignatureValid && err != nil:
		t.Fatalf("signature should verify: %v", err)
	case !exp.Update.SignatureValid && err == nil:
		t.Fatal("signature verified but the vector expects it to fail")
	case !exp.Update.SignatureValid:
		return
	}

	if d.FirmwareVersion != exp.Update.FirmwareVersion {
		t.Errorf("firmware_version = %q, want %q", d.FirmwareVersion,
			exp.Update.FirmwareVersion)
	}
	if d.MinFirmwareVersion != exp.Update.MinFirmwareVersion {
		t.Errorf("min_firmware_version = %q, want %q", d.MinFirmwareVersion,
			exp.Update.MinFirmwareVersion)
	}
	if d.ImageLength != exp.Update.ImageLength {
		t.Errorf("image_length = %d, want %d", d.ImageLength, exp.Update.ImageLength)
	}
	if got := hex.EncodeToString(d.ImageSHA256[:]); got != exp.Update.ImageSHA256Hex {
		t.Errorf("image_sha256 = %s, want %s", got, exp.Update.ImageSHA256Hex)
	}
}
