package format

import (
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The conformance runner checks this implementation against the committed
// vectors in fixtures/format-v2/.
//
// For Go this is a regression guard rather than an independent check: the
// vectors are generated by cmd/mkvectors, which uses this package. Its value is
// that any change to the format code makes the committed vectors fail, forcing
// a deliberate regeneration and a visible diff instead of a silent format
// change. The same runner shape is what the C and Rust implementations must
// satisfy, where the check is genuinely independent.

const vectorDir = "../../fixtures/format-v2"

type vectorExpectation struct {
	Name        string `json:"name"`
	Description string `json:"description"`

	Scan *struct {
		StopReason         string         `json:"stop_reason"`
		FramesRetained     int            `json:"frames_retained"`
		StopOffset         int            `json:"stop_offset"`
		DiscardedTailBytes uint32         `json:"discarded_tail_bytes"`
		UnknownTypeCount   int            `json:"unknown_type_count"`
		RecordCounts       map[string]int `json:"record_counts"`
		FirstSeq           *uint32        `json:"first_seq"`
		LastSeq            *uint32        `json:"last_seq"`
	} `json:"scan"`

	Header *struct {
		ParseError string `json:"parse_error"`
	} `json:"header"`

	Manifest *struct {
		Valid              bool   `json:"valid"`
		SignatureValid     bool   `json:"signature_valid"`
		ContentRootHex     string `json:"content_root_hex"`
		DevicePublicKeyHex string `json:"device_public_key_hex"`
		CanonicalBytesHex  string `json:"canonical_bytes_sha256_hex"`
	} `json:"manifest"`

	Receipt *struct {
		SignatureValid     bool   `json:"signature_valid"`
		Acknowledges       bool   `json:"acknowledges_uploaded_root"`
		UploadedRootHex    string `json:"uploaded_content_root_hex"`
		ReceiptRootHex     string `json:"receipt_content_root_hex"`
		ServerPublicKeyHex string `json:"server_public_key_hex"`
	} `json:"receipt"`

	Merkle *struct {
		RootHex string   `json:"root_hex"`
		Leaves  []string `json:"leaves_hex"`
	} `json:"merkle"`
}

func TestConformanceVectors(t *testing.T) {
	entries, err := os.ReadDir(vectorDir)
	if err != nil {
		t.Skipf("vectors not generated (%v); run: go run ./cmd/mkvectors -out ../fixtures/format-v2", err)
	}

	checked := 0
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}

		dir := filepath.Join(vectorDir, e.Name())
		raw, err := os.ReadFile(filepath.Join(dir, "expected.json"))
		if err != nil {
			t.Errorf("%s: no expected.json: %v", e.Name(), err)
			continue
		}

		var exp vectorExpectation
		if err := json.Unmarshal(raw, &exp); err != nil {
			// Multi-segment vectors use a different shape; they are covered by
			// TestValidMultiSegment.
			continue
		}

		t.Run(e.Name(), func(t *testing.T) {
			switch {
			case exp.Scan != nil:
				checkScanVector(t, dir, &exp)
			case exp.Header != nil:
				checkHeaderVector(t, dir)
			case exp.Manifest != nil:
				checkManifestVector(t, dir, &exp)
			case exp.Receipt != nil:
				checkReceiptVector(t, dir, &exp)
			case exp.Merkle != nil:
				checkMerkleVector(t, &exp)
			default:
				t.Skip("no checkable expectation")
			}
		})
		checked++
	}

	if checked == 0 {
		t.Error("no vectors were checked")
	}
	t.Logf("checked %d vectors", checked)
}

func checkScanVector(t *testing.T, dir string, exp *vectorExpectation) {
	t.Helper()

	b, err := os.ReadFile(filepath.Join(dir, "segment.bin"))
	if err != nil {
		t.Fatalf("read segment.bin: %v", err)
	}

	res, err := ScanSegment(b, ScanState{})
	if err != nil {
		t.Fatalf("ScanSegment: %v", err)
	}

	if got := res.Stop.String(); got != exp.Scan.StopReason {
		t.Errorf("stop_reason = %q, want %q (%s)", got, exp.Scan.StopReason, res.StopDetail)
	}
	if len(res.Frames) != exp.Scan.FramesRetained {
		t.Errorf("frames_retained = %d, want %d", len(res.Frames), exp.Scan.FramesRetained)
	}
	if res.StopOffset != exp.Scan.StopOffset {
		t.Errorf("stop_offset = %d, want %d", res.StopOffset, exp.Scan.StopOffset)
	}
	if res.DiscardedTailBytes != exp.Scan.DiscardedTailBytes {
		t.Errorf("discarded_tail_bytes = %d, want %d", res.DiscardedTailBytes, exp.Scan.DiscardedTailBytes)
	}
	if res.UnknownTypeCount != exp.Scan.UnknownTypeCount {
		t.Errorf("unknown_type_count = %d, want %d", res.UnknownTypeCount, exp.Scan.UnknownTypeCount)
	}

	for name, want := range exp.Scan.RecordCounts {
		found := 0
		for rt, n := range res.RecordCounts {
			if rt.String() == name {
				found = n
			}
		}
		if found != want {
			t.Errorf("record_counts[%s] = %d, want %d", name, found, want)
		}
	}

	if exp.Scan.FirstSeq != nil {
		if len(res.Frames) == 0 {
			t.Error("expected frames, got none")
		} else if res.Frames[0].Seq != *exp.Scan.FirstSeq {
			t.Errorf("first_seq = %d, want %d", res.Frames[0].Seq, *exp.Scan.FirstSeq)
		}
	}
	if exp.Scan.LastSeq != nil && len(res.Frames) > 0 {
		if got := res.Frames[len(res.Frames)-1].Seq; got != *exp.Scan.LastSeq {
			t.Errorf("last_seq = %d, want %d", got, *exp.Scan.LastSeq)
		}
	}
}

func checkHeaderVector(t *testing.T, dir string) {
	t.Helper()

	b, err := os.ReadFile(filepath.Join(dir, "segment.bin"))
	if err != nil {
		t.Fatalf("read segment.bin: %v", err)
	}

	if _, err := ScanSegment(b, ScanState{}); err == nil {
		t.Error("expected a header parse error, got none")
	}
}

func checkManifestVector(t *testing.T, dir string, exp *vectorExpectation) {
	t.Helper()

	encoded, err := os.ReadFile(filepath.Join(dir, "manifest.cbor"))
	if err != nil {
		t.Fatalf("read manifest.cbor: %v", err)
	}
	sig, err := os.ReadFile(filepath.Join(dir, "manifest.sig"))
	if err != nil {
		t.Fatalf("read manifest.sig: %v", err)
	}
	pub, err := hex.DecodeString(exp.Manifest.DevicePublicKeyHex)
	if err != nil {
		t.Fatalf("decode device public key: %v", err)
	}

	// The manifest bytes must parse as canonical regardless of signature
	// validity: a bad signature does not make the encoding malformed.
	m, parseErr := ParseManifest(encoded)
	if exp.Manifest.Valid && parseErr != nil {
		t.Fatalf("ParseManifest: %v", parseErr)
	}

	_, verifyErr := VerifyManifest(encoded, sig, ed25519.PublicKey(pub))
	if exp.Manifest.SignatureValid && verifyErr != nil {
		t.Errorf("signature should verify: %v", verifyErr)
	}
	if !exp.Manifest.SignatureValid && verifyErr == nil {
		t.Error("signature verified but the vector expects it to fail")
	}

	if m == nil {
		return
	}

	wantRoot, err := hex.DecodeString(exp.Manifest.ContentRootHex)
	if err != nil {
		t.Fatalf("decode content root: %v", err)
	}
	if string(m.ContentRoot[:]) != string(wantRoot) {
		t.Errorf("content_root = %x, want %x", m.ContentRoot, wantRoot)
	}
	if err := m.VerifyContentRoot(); err != nil {
		t.Errorf("VerifyContentRoot: %v", err)
	}

	// Re-encoding must reproduce the committed bytes exactly. This is the
	// check that catches an accidental encoding change.
	if exp.Manifest.CanonicalBytesHex != "" {
		reencoded, err := m.MarshalCBOR()
		if err != nil {
			t.Fatalf("MarshalCBOR: %v", err)
		}
		digest := sha256.Sum256(reencoded)
		if hex.EncodeToString(digest[:]) != exp.Manifest.CanonicalBytesHex {
			t.Errorf("re-encoded manifest digest = %x, want %s — the encoding changed; "+
				"regenerate the vectors deliberately if this is intended",
				digest, exp.Manifest.CanonicalBytesHex)
		}
	}
}

func checkReceiptVector(t *testing.T, dir string, exp *vectorExpectation) {
	t.Helper()

	encoded, err := os.ReadFile(filepath.Join(dir, "receipt.cbor"))
	if err != nil {
		t.Fatalf("read receipt.cbor: %v", err)
	}
	pub, err := hex.DecodeString(exp.Receipt.ServerPublicKeyHex)
	if err != nil {
		t.Fatalf("decode server public key: %v", err)
	}

	r, err := ParseReceipt(encoded)
	if err != nil {
		t.Fatalf("ParseReceipt: %v", err)
	}

	sigErr := r.Verify(ed25519.PublicKey(pub))
	if exp.Receipt.SignatureValid && sigErr != nil {
		t.Errorf("signature should verify: %v", sigErr)
	}
	if !exp.Receipt.SignatureValid && sigErr == nil {
		t.Error("signature verified but the vector expects it to fail")
	}

	uploaded, err := hex.DecodeString(exp.Receipt.UploadedRootHex)
	if err != nil {
		t.Fatalf("decode uploaded root: %v", err)
	}
	var uploadedRoot [32]byte
	copy(uploadedRoot[:], uploaded)

	ackErr := r.VerifyAcknowledges(ed25519.PublicKey(pub), uploadedRoot)
	if exp.Receipt.Acknowledges && ackErr != nil {
		t.Errorf("receipt should acknowledge the upload: %v", ackErr)
	}
	if !exp.Receipt.Acknowledges && ackErr == nil {
		t.Error("receipt accepted as an acknowledgement but the vector expects rejection")
	}
}

func checkMerkleVector(t *testing.T, exp *vectorExpectation) {
	t.Helper()

	// Leaves present: check the tree construction directly.
	if exp.Merkle.Leaves != nil {
		leaves := make([][32]byte, 0, len(exp.Merkle.Leaves))
		for _, h := range exp.Merkle.Leaves {
			b, err := hex.DecodeString(h)
			if err != nil {
				t.Fatalf("decode leaf: %v", err)
			}
			var l [32]byte
			copy(l[:], b)
			leaves = append(leaves, l)
		}

		root := MerkleRoot(leaves)
		if hex.EncodeToString(root[:]) != exp.Merkle.RootHex {
			t.Errorf("root = %x, want %s", root, exp.Merkle.RootHex)
		}
		return
	}

	// Otherwise it is a content-root vector described by members.json.
	t.Skip("content root checked via members.json in TestContentRootIsOrderIndependent")
}
