package format

import "fmt"

// PolicySnapshot is the active capture policy a bundle was produced under
// (§4.9).
//
// Recorded because a version number identifies a policy without describing one.
// Interpreting an old bundle from PolicyVersion alone would mean finding the
// firmware build that defined that version; the values make a trip captured
// under thresholds nobody remembers explainable from the trip.
// JSON tags mirror the specification's field names, so the committed vectors
// and this struct align by construction rather than by a parallel definition
// somebody has to keep in step.
type PolicySnapshot struct {
	PolicyVersion uint8 `json:"policy_version"`

	GNSSPeriodMS   uint16 `json:"gnss_period_ms"`
	IMUWindowMS    uint16 `json:"imu_window_ms"`
	OBDPeriodMS    uint16 `json:"obd_period_ms"`
	HealthPeriodMS uint32 `json:"health_period_ms"`

	StartScoreThresholdE2 uint16 `json:"start_score_threshold_e2"`
	StopScoreThresholdE2  uint16 `json:"stop_score_threshold_e2"`
	StartDwellMS          uint32 `json:"start_dwell_ms"`
	StopDwellMS           uint32 `json:"stop_dwell_ms"`

	MotionAccelRMSmg uint16 `json:"motion_accel_rms_mg"`
	MotionSpeedCMPS  uint16 `json:"motion_speed_cmps"`

	PrerollWindowMS    uint32 `json:"preroll_window_ms"`
	PrerollRingSamples uint16 `json:"preroll_ring_samples"`
	SegmentMaxBytes    uint32 `json:"segment_max_bytes"`

	// AdaptiveSampling means the periods above are upper bounds during a trip
	// rather than fixed rates (§4.9.1). Adaptation may only add detail, so a
	// reader's floor of one record per nominal period still holds.
	AdaptiveSampling bool `json:"adaptive_sampling"`
}

// Policy snapshot CBOR keys.
const (
	polKeyPolicyVersion    = 1
	polKeyGNSSPeriod       = 2
	polKeyIMUWindow        = 3
	polKeyOBDPeriod        = 4
	polKeyHealthPeriod     = 5
	polKeyStartScore       = 6
	polKeyStopScore        = 7
	polKeyStartDwell       = 8
	polKeyStopDwell        = 9
	polKeyMotionAccel      = 10
	polKeyMotionSpeed      = 11
	polKeyPrerollWindow    = 12
	polKeyPrerollSamples   = 13
	polKeySegmentMax       = 14
	polKeyAdaptiveSampling = 15

	policyFieldCount = 15
)

// MarshalCBOR encodes the snapshot deterministically.
//
// The reference implementation can produce every record it can consume. Without
// that, the committed vectors would have to be generated by whichever
// implementation happened to emit a record first, which is exactly the
// asymmetry the three-implementation rule exists to prevent.
func (p *PolicySnapshot) MarshalCBOR() ([]byte, error) {
	e := &cborEncoder{}
	e.mapHeader(policyFieldCount)

	e.key(polKeyPolicyVersion)
	e.uint(uint64(p.PolicyVersion))
	e.key(polKeyGNSSPeriod)
	e.uint(uint64(p.GNSSPeriodMS))
	e.key(polKeyIMUWindow)
	e.uint(uint64(p.IMUWindowMS))
	e.key(polKeyOBDPeriod)
	e.uint(uint64(p.OBDPeriodMS))
	e.key(polKeyHealthPeriod)
	e.uint(uint64(p.HealthPeriodMS))
	e.key(polKeyStartScore)
	e.uint(uint64(p.StartScoreThresholdE2))
	e.key(polKeyStopScore)
	e.uint(uint64(p.StopScoreThresholdE2))
	e.key(polKeyStartDwell)
	e.uint(uint64(p.StartDwellMS))
	e.key(polKeyStopDwell)
	e.uint(uint64(p.StopDwellMS))
	e.key(polKeyMotionAccel)
	e.uint(uint64(p.MotionAccelRMSmg))
	e.key(polKeyMotionSpeed)
	e.uint(uint64(p.MotionSpeedCMPS))
	e.key(polKeyPrerollWindow)
	e.uint(uint64(p.PrerollWindowMS))
	e.key(polKeyPrerollSamples)
	e.uint(uint64(p.PrerollRingSamples))
	e.key(polKeySegmentMax)
	e.uint(uint64(p.SegmentMaxBytes))
	e.key(polKeyAdaptiveSampling)
	if p.AdaptiveSampling {
		e.uint(1)
	} else {
		e.uint(0)
	}

	return e.buf, nil
}

// ParsePolicySnapshot decodes a POLICY_SNAPSHOT payload.
//
// Strict about canonical encoding for the same reason the manifest decoder is:
// a map this implementation would not itself have produced cannot be compared
// byte-for-byte against another bundle's, which is what makes grouping bundles
// by policy meaningful without trusting the version number.
func ParsePolicySnapshot(p []byte) (*PolicySnapshot, error) {
	d := &cborDecoder{buf: p}

	n, err := d.mapHeader()
	if err != nil {
		return nil, fmt.Errorf("policy snapshot: %w", err)
	}
	if n != policyFieldCount {
		return nil, fmt.Errorf("policy snapshot has %d fields, want %d",
			n, policyFieldCount)
	}

	var out PolicySnapshot

	for i := 0; i < n; i++ {
		key, err := d.uint()
		if err != nil {
			return nil, fmt.Errorf("policy snapshot key %d: %w", i, err)
		}

		v, err := d.uint()
		if err != nil {
			return nil, fmt.Errorf("policy snapshot value for key %d: %w", key, err)
		}

		switch key {
		case polKeyPolicyVersion:
			out.PolicyVersion = uint8(v)
		case polKeyGNSSPeriod:
			out.GNSSPeriodMS = uint16(v)
		case polKeyIMUWindow:
			out.IMUWindowMS = uint16(v)
		case polKeyOBDPeriod:
			out.OBDPeriodMS = uint16(v)
		case polKeyHealthPeriod:
			out.HealthPeriodMS = uint32(v)
		case polKeyStartScore:
			out.StartScoreThresholdE2 = uint16(v)
		case polKeyStopScore:
			out.StopScoreThresholdE2 = uint16(v)
		case polKeyStartDwell:
			out.StartDwellMS = uint32(v)
		case polKeyStopDwell:
			out.StopDwellMS = uint32(v)
		case polKeyMotionAccel:
			out.MotionAccelRMSmg = uint16(v)
		case polKeyMotionSpeed:
			out.MotionSpeedCMPS = uint16(v)
		case polKeyPrerollWindow:
			out.PrerollWindowMS = uint32(v)
		case polKeyPrerollSamples:
			out.PrerollRingSamples = uint16(v)
		case polKeySegmentMax:
			out.SegmentMaxBytes = uint32(v)
		case polKeyAdaptiveSampling:
			out.AdaptiveSampling = v != 0
		default:
			// An unknown key means newer firmware. Refuse rather than ignore:
			// the field count is fixed, so an unexpected key means this decoder
			// does not understand the policy it is being asked to describe, and
			// reporting a partial policy as complete would be worse than
			// reporting none.
			return nil, fmt.Errorf("policy snapshot has unknown key %d; this "+
				"build does not understand the policy", key)
		}
	}

	// Trailing bytes would mean the payload carries something this decoder did
	// not account for, which is the same hazard as an unknown key.
	if !d.atEnd() {
		return nil, fmt.Errorf("policy snapshot has %d trailing byte(s)",
			len(p)-d.pos)
	}

	return &out, nil
}
