package main

import "strings"

// readmeTemplate is the fixtures README. It uses § for a backtick so the text
// can live in a raw string, and is filled by fmt.Sprintf with, in order: the
// vector count, the root key hex, its version, the alternate root key hex and
// its version. Keep literal percent signs out of it.
var readmeTemplate = strings.ReplaceAll(`# Bundle format v3 conformance vectors

Generated by §server/cmd/mkvectors§. Do not edit by hand. Regenerate with:

    go run ./cmd/mkvectors        (writes into $CAIRN_CONTRACTS/format/v3/vectors)

%d vectors. Each directory holds the input bytes plus an §expected.json§
stating the verdict and derived values. A conformance runner needs no knowledge
of any particular implementation: the inputs and expectations together define
the behaviour that contracts/format/v3/spec.md specifies.

An implementation is conformant when it produces the stated verdict for every
vector, and byte-identical output for the encoding vectors.

Generation is deterministic. Keys come from fixed seeds, every timestamp is a
constant, and frame nonces come from a fixed per-writer stream instead of the
hardware RNG, so regenerating produces an empty diff.

## THESE ARE PUBLIC TEST KEYS

Everything below is committed to a public repository. **These keys protect
nothing.** Never provision them onto a device, never load them into a real
keystore, never sign or encrypt anything real with them. They exist so that
firmware, emulator and server can prove they derive the same keys and decrypt
the same bytes.

| Key | Value |
|---|---|
| Storage root K_root, version %[3]d | §%[2]s§ |
| Alternate storage root, version %[5]d (used only by §wrong-key-version§) | §%[4]s§ |

The same material, plus the vector identities and a worked HKDF example, is in
§keys.json§. The Ed25519 signing keys are fixed seeds in §cmd/mkvectors§ and the
public halves are in the manifest, receipt and update expectations.

Vector identities: device_id §10..1f§, boot_id §a0..af§, vehicle_id §30..3f§,
assignment_id §50..5f§ (each 16 bytes, incrementing from the first byte shown),
device_counter 42, storage_key_version 1.

A verifier is given K_root version 1 only. Its segment key for every segment is
derived from the segment's own header with HKDF-SHA256 as the spec defines.

## Reading a vector

| File | Meaning |
|---|---|
| §segment.bin§ | A segment to scan. Start with the zero ScanState unless the expectation says otherwise. |
| §segment-N.bin§ | Multi-segment vectors. Scan in order, threading each scan's resulting state into the next. |
| §manifest.cbor§ / §manifest.sig§ | Deterministic CBOR manifest and its detached Ed25519 signature. |
| §seg-*.seg§ / §journal.seg§ | Bundle members for the manifest binding vectors. |
| §receipt.cbor§ | A server receipt, signature inline at key 11. |
| §members.json§ | Member list for content-root vectors. |
| §keys.json§ | The test key material (top level, shared by all vectors). |
| §descriptor.cbor§ / §descriptor.sig§ | An update descriptor and its detached signature. |
| §expected.json§ | The verdict. |

## Two scans per segment

Every segment vector states two verdicts.

- §scan§ is the **structural** verdict: scan with **no key**. Torn tails, frame
  CRCs, the prev_crc32 chain and sequence are all computed over ciphertext, so
  this works for anyone who holds the bytes, including a thief.
- §keyed§ is the verdict of scanning with K_root version 1. It adds
  authentication of every frame. §error§ is set instead of the scan fields when
  the segment cannot be keyed at all. §segment_key_hex§ is the derived K_seg for
  the header as it appears in the file, so an implementation can check its HKDF
  separately from its AEAD. §plaintext_sha256_hex§ is SHA-256 over, for each
  retained frame, u32le(plaintext length) followed by the plaintext.

The vectors named §auth-tag-tampered§, §frame-moved-between-segments§ and
§wrong-vehicle-key§ are the ones where the two verdicts differ: structurally
clean, cryptographically rejected.

## Stop reasons

| Reason | Meaning |
|---|---|
| §EOF§ | Clean: the whole segment parsed. |
| §TORN_TAIL§ | Ends mid-frame. Expected after a power cut; frames before the tear are retained. |
| §CORRUPT_FRAME§ | A frame CRC mismatched. Corruption is isolated to that frame. |
| §CHAIN_BREAK§ | prev_crc32 did not match: a record was removed, reordered or spliced. |
| §SEQ_GAP§ | The sequence number skipped a value. |
| §AUTH_FAILED§ | Keyed scans only. CRC, chain and sequence were fine but the authentication tag was not. Never produced by a structural scan. |

## Negative vectors

Every vector below must be REFUSED, and for the stated reason. Passing only the
valid vectors proves an implementation accepts what it should; these prove it
rejects what it must.

| Vectors | What is wrong | Verdict field |
|---|---|---|
| §bad-header-crc§, §header-bad-magic§, §header-unsupported-format-version§, §header-short§ | The segment header | §header.parse_error§: §bad_header_crc§, §bad_magic§, §unsupported_format_version§, §short_header§. Refused by a keyless and a keyed scan alike. |
| §bad-frame-crc§, §chain-break-spliced§, §seq-gap§, §torn-tail-*§ | Frame structure | §scan.stop_reason§ |
| §auth-tag-tampered§, §frame-header-tampered§, §frame-moved-between-segments§, §wrong-vehicle-key§, §wrong-key-version§ | Authentication; structurally clean | §keyed§ |
| §manifest-bad-signature§, §manifest-tampered-body§, §manifest-wrong-device-key§ | The manifest signature | §manifest.signature_valid§ false, §valid§ true |
| §manifest-unsupported-version§, §manifest-non-canonical§, §manifest-missing-mandatory-field§ | The manifest bytes, correctly signed | §manifest.valid§ false |
| §manifest-segment-header-mismatch§ (assignment_id), §manifest-device-id-mismatch§, §manifest-boot-id-mismatch§, §manifest-vehicle-id-mismatch§, §manifest-device-counter-mismatch§, §manifest-key-version-mismatch§, §manifest-segment-index-mismatch§, §manifest-journal-index-mismatch§, §manifest-segment-gap§ | A segment that does not belong to its manifest | §binding.mismatched_field§ |
| §receipt-wrong-content-root§, §receipt-bad-signature§, §receipt-wrong-server-key§, §receipt-tampered-content-root§ | The receipt is not an acknowledgement | §receipt.signature_valid§, §receipt.acknowledges_uploaded_root§ |
| §receipt-unsupported-version§, §receipt-non-canonical§, §receipt-truncated§, §receipt-trailing-bytes§ | The receipt bytes | §receipt.parse_error§: §unsupported_version§, §non_canonical§, §truncated§, §trailing_bytes§ |
| §update-descriptor-bad-signature§, §update-descriptor-tampered-body§, §update-descriptor-wrong-key§ | The update descriptor signature | §update.signature_valid§ false |

For a manifest with §valid: false§ the whole manifest is refused: the verdict is
that parsing fails, and §signature_valid§ is false only in the sense that
verification (signature, then parse) does not succeed. The Ed25519 signature is
correct over those bytes, so an implementation whose verify call checks the
signature alone must still refuse at parse and not assert the signature field.
A §receipt.parse_error§ names the reason; implementations that cannot tell
every reason apart must still refuse every one.

## Keyed errors

| Error | Meaning |
|---|---|
| §KEY_VERSION_MISMATCH§ | The segment's storage_key_version is not the one the verifier holds. A key is missing; the segment is not tampered with. |
| §NO_KEY§ | The verifier holds no key for the segment's device. |
`, "§", "`")
